//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp_Lab1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comp_Lab1.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компилятор.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string colCode {
            get {
                return ResourceManager.GetString("colCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string ColFile {
            get {
                return ResourceManager.GetString("ColFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный фрагмент.
        /// </summary>
        internal static string colFragment {
            get {
                return ResourceManager.GetString("colFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка.
        /// </summary>
        internal static string ColLine {
            get {
                return ResourceManager.GetString("ColLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string ColMessage {
            get {
                return ResourceManager.GetString("ColMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение.
        /// </summary>
        internal static string colPos {
            get {
                return ResourceManager.GetString("colPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип лексемы.
        /// </summary>
        internal static string colType {
            get {
                return ResourceManager.GetString("colType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string LangEn {
            get {
                return ResourceManager.GetString("LangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string LangRu {
            get {
                return ResourceManager.GetString("LangRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Классификация грамматики.
        /// </summary>
        internal static string MenuClass {
            get {
                return ResourceManager.GetString("MenuClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        internal static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        internal static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список литературы.
        /// </summary>
        internal static string MenuDocs {
            get {
                return ResourceManager.GetString("MenuDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правка.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовый пример.
        /// </summary>
        internal static string MenuExample {
            get {
                return ResourceManager.GetString("MenuExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грамматика.
        /// </summary>
        internal static string MenuGrammar {
            get {
                return ResourceManager.GetString("MenuGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string MenuHelpRoot {
            get {
                return ResourceManager.GetString("MenuHelpRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string MenuLangRoot {
            get {
                return ResourceManager.GetString("MenuLangRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод анализа.
        /// </summary>
        internal static string MenuMethod {
            get {
                return ResourceManager.GetString("MenuMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить.
        /// </summary>
        internal static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пуск.
        /// </summary>
        internal static string MenuRun {
            get {
                return ResourceManager.GetString("MenuRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделить всё.
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызов справки.
        /// </summary>
        internal static string MenuShowHelp {
            get {
                return ResourceManager.GetString("MenuShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходный код программы.
        /// </summary>
        internal static string MenuSource {
            get {
                return ResourceManager.GetString("MenuSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постановка задачи.
        /// </summary>
        internal static string MenuTask {
            get {
                return ResourceManager.GetString("MenuTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to стр..
        /// </summary>
        internal static string MsgLine {
            get {
                return ResourceManager.GetString("MsgLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый файл.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оператор присваивания.
        /// </summary>
        internal static string TypeAssign {
            get {
                return ResourceManager.GetString("TypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to незакрытая строка.
        /// </summary>
        internal static string TypeErrorString {
            get {
                return ResourceManager.GetString("TypeErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недопустимый символ.
        /// </summary>
        internal static string TypeErrorSymbol {
            get {
                return ResourceManager.GetString("TypeErrorSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to идентификатор.
        /// </summary>
        internal static string TypeIdentifier {
            get {
                return ResourceManager.GetString("TypeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ключевое слово.
        /// </summary>
        internal static string TypeKeyword {
            get {
                return ResourceManager.GetString("TypeKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to конец оператора.
        /// </summary>
        internal static string TypeSemicolon {
            get {
                return ResourceManager.GetString("TypeSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to строковая константа.
        /// </summary>
        internal static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пробел.
        /// </summary>
        internal static string TypeWhitespace {
            get {
                return ResourceManager.GetString("TypeWhitespace", resourceCulture);
            }
        }
    }
}
